// Turns the SVGs in assets/icons into components/customIcons.ts, so they draw
// with react-native-svg on every build (Expo and Vite load .svg files
// differently). Run after adding or changing an icon: npm run icons
const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.join(__dirname, '..', 'assets', 'icons');
const OUT = path.join(__dirname, '..', 'components', 'customIcons.ts');
// Drawn in this colour in the files; replaced by the icon's colour prop.
const THEME_COLOR = '#F8E3E3';
const TAGS = ['path', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon'];

const camel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

function parseAttrs(source) {
  const attrs = {};
  for (const [, name, value] of source.matchAll(/([a-zA-Z-:]+)="([^"]*)"/g)) {
    if (name === 'xmlns' || name.startsWith('xmlns:')) continue;
    attrs[camel(name)] = value.toUpperCase() === THEME_COLOR ? 'currentColor' : value;
  }
  return attrs;
}

const icons = {};
for (const file of fs.readdirSync(ICONS_DIR).filter((f) => f.endsWith('.svg')).sort()) {
  const svg = fs.readFileSync(path.join(ICONS_DIR, file), 'utf8');
  const root = svg.match(/<svg\b([^>]*)>/);
  if (!root) { console.warn(`${file}: no <svg>, skipped`); continue; }
  const rootAttrs = parseAttrs(root[1]);
  const viewBox = rootAttrs.viewBox || `0 0 ${parseFloat(rootAttrs.width)} ${parseFloat(rootAttrs.height)}`;
  // Presentation attributes set on <svg> (e.g. fill="none") apply to every
  // shape that doesn't set its own; without this, outlines fill black.
  const inherited = {};
  for (const key of ['fill', 'stroke', 'strokeWidth', 'strokeLinecap', 'strokeLinejoin', 'fillRule']) {
    if (rootAttrs[key] != null) inherited[key] = rootAttrs[key];
  }
  const elements = [];
  for (const [, tag, attrSource] of svg.matchAll(/<([a-z]+)\b([^>]*?)\/?>/g)) {
    if (tag === 'svg') continue;
    if (!TAGS.includes(tag)) { console.warn(`${file}: <${tag}> not supported, skipped`); continue; }
    elements.push({ tag, attrs: { ...inherited, ...parseAttrs(attrSource) } });
  }
  icons[file.replace(/\.svg$/, '')] = { viewBox, elements };
}

const out = `// Generated by scripts/build-icons.js from assets/icons — don't edit by hand.
// "currentColor" stands for the colour passed to <CustomIcon>.

export type CustomIconElement = { tag: ${TAGS.map((t) => `'${t}'`).join(' | ')}; attrs: Record<string, string> };
export type CustomIconData = { viewBox: string; elements: CustomIconElement[] };

export const CUSTOM_ICONS: Record<string, CustomIconData> = ${JSON.stringify(icons, null, 2)};
`;
fs.writeFileSync(OUT, out);
console.log(`${Object.keys(icons).length} icons -> ${path.relative(process.cwd(), OUT)}: ${Object.keys(icons).join(', ')}`);
