import { StyleSheet } from 'react-native';
import { d } from '../utils/scale';
import { C, HELV, VIGA } from './theme';

// Home (PDF pages 1, 14, 15). Measurements in Figma px (844x390 frame).
export const SETTINGS_PANEL_W = d(342);

export const styles = StyleSheet.create({
  window: { flex: 1, backgroundColor: C.bg, overflow: 'hidden' },

  // Robot selector
  robotArea: { position: 'absolute', top: d(28), left: d(35), zIndex: 20 },
  robotPill: {
    width: d(190),
    height: d(49),
    borderRadius: d(13),
    backgroundColor: C.panel,
    paddingHorizontal: d(14),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  robotName: { color: C.text, fontFamily: HELV, fontWeight: '700', fontSize: d(13.5) },
  robotSub: { color: C.textDim, fontFamily: HELV, fontSize: d(10), marginTop: d(1) },
  robotMenu: {
    marginTop: d(9),
    width: d(190),
    borderWidth: 1,
    borderColor: C.muted,
    backgroundColor: C.panel,
    borderRadius: d(13),
    padding: d(6),
    gap: d(4),
  },
  robotOption: {
    paddingHorizontal: d(8),
    paddingVertical: d(6),
    borderRadius: d(9),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  robotOptionSelected: { backgroundColor: '#7A2C2C' },
  robotAdd: { height: d(26), borderRadius: d(9), backgroundColor: C.muted, alignItems: 'center', justifyContent: 'center' },

  topRight: { position: 'absolute', top: d(19), right: d(20), flexDirection: 'row', gap: d(10), zIndex: 20 },
  iconButton: {
    width: d(49),
    height: d(49),
    borderRadius: d(13),
    backgroundColor: C.panel,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Logo + main actions (right-hand column)
  mainColumn: { position: 'absolute', left: d(423), width: d(326), top: d(78) },
  logoBlock: { alignItems: 'center', marginBottom: d(24) },
  logoText: {
    color: C.text,
    fontFamily: VIGA,
    fontSize: d(90),
    lineHeight: d(96),
    letterSpacing: d(1),
  },
  logoAccent: { color: C.red },
  logoSub: {
    alignSelf: 'flex-start',
    marginLeft: d(65),
    marginTop: d(-10),
    color: '#A88C8C',
    fontFamily: HELV,
    fontSize: d(17),
  },
  primaryButton: {
    height: d(54),
    borderRadius: d(12),
    backgroundColor: C.red,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: d(14),
  },
  secondaryButton: {
    height: d(54),
    marginTop: d(13),
    borderRadius: d(12),
    backgroundColor: '#3D3434',
    borderWidth: 1,
    borderColor: '#554848',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: d(12),
  },
  primaryButtonText: { color: C.text, fontFamily: VIGA, fontSize: d(17), letterSpacing: 0.5 },

  // Settings panel
  dim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(20,16,16,0.45)', zIndex: 40 },
  settingsPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: SETTINGS_PANEL_W,
    backgroundColor: C.panel,
    borderLeftWidth: 1,
    borderLeftColor: C.muted,
    paddingHorizontal: d(24),
    paddingTop: d(22),
    zIndex: 50,
  },
  settingsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: d(20) },
  settingsTitle: { color: C.text, fontFamily: VIGA, fontSize: d(20) },
  closeButton: {
    width: d(42),
    height: d(42),
    borderRadius: d(12),
    backgroundColor: '#5A4D4D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsCard: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.muted,
    borderRadius: d(16),
    padding: d(18),
    marginBottom: d(18),
  },
  settingsRow: { flexDirection: 'row', alignItems: 'center', gap: d(14) },
  cardTitle: { color: C.text, fontFamily: HELV, fontWeight: '700', fontSize: d(14) },
  cardText: { color: C.textDim, fontFamily: HELV, fontSize: d(10.5), lineHeight: d(14), marginTop: d(6) },

  toggle: {
    width: d(58),
    height: d(30),
    borderRadius: d(15),
    backgroundColor: '#A39393',
    padding: d(3),
    justifyContent: 'center',
  },
  toggleOn: { backgroundColor: C.red },
  toggleThumb: { width: d(24), height: d(24), borderRadius: d(12), backgroundColor: '#D9D9D9' },
  toggleThumbOn: { alignSelf: 'flex-end' },

  sliderArea: { height: d(26), justifyContent: 'center', marginTop: d(12) },
  sliderTrack: { height: d(6), borderRadius: d(3), backgroundColor: '#5A4D4D', overflow: 'hidden' },
  sliderFill: { height: '100%', backgroundColor: C.red },
  sliderThumb: {
    position: 'absolute',
    top: d(4.5),
    width: d(17),
    height: d(17),
    marginLeft: d(-8.5),
    borderRadius: d(8.5),
    backgroundColor: C.red,
  },

  // Login modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(20,16,16,0.6)', alignItems: 'center', justifyContent: 'center' },
  modalCard: {
    width: d(360),
    backgroundColor: C.panel,
    borderRadius: d(20),
    borderWidth: 1,
    borderColor: C.muted,
    padding: d(22),
  },
  fieldLabel: { color: C.textSoft, fontFamily: HELV, fontWeight: '700', fontSize: d(10.5), marginTop: d(8), marginBottom: d(6) },
  input: {
    height: d(38),
    backgroundColor: C.input,
    borderWidth: 1,
    borderColor: C.inputBorder,
    borderRadius: d(12),
    paddingHorizontal: d(14),
    color: C.text,
    fontFamily: HELV,
    fontWeight: '700',
    fontSize: d(13),
  },
  modalActions: { flexDirection: 'row', gap: d(10), marginTop: d(16) },
  modalButton: { flex: 1, height: d(42), marginTop: 0 },
  modalButtonText: { color: C.text, fontFamily: HELV, fontWeight: '700', fontSize: d(14) },
});
