import { StyleSheet } from 'react-native';
import { s, f } from '../utils/scale';

const RED = '#f23b3f';
const BG = '#292222';
const PANEL = '#4b3f3f';
const TEXT_LIGHT = '#f6e7e7';

export const styles = StyleSheet.create({
  window: {
    flex: 1,
    backgroundColor: BG,
    overflow: 'hidden',
  },

  topBar: {
    position: 'absolute',
    top: s(24),
    left: s(24),
    right: s(28),
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusPill: {
    height: s(36),
    minWidth: s(200),
    paddingLeft: s(12),
    paddingRight: s(8),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
  },
  authButton: {
    height: s(36),
    paddingHorizontal: s(14),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  authButtonText: {
    color: RED,
    fontSize: f(13),
    fontFamily: 'monospace',
  },

  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: s(24),
  },
  logoImage: {
    width: s(420),
    height: s(200),
    marginBottom: s(50),
  },

  buttonWrapper: {
    width: '60%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: s(60),
  },
  mainButton: {
    flex: 1,
    height: s(78),
    borderRadius: 6,
    borderWidth: 2,
    borderColor: RED,
    backgroundColor: PANEL,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: RED,
    fontSize: f(24),
    fontFamily: 'monospace',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    paddingTop: s(72),
    paddingRight: s(28),
  },
  authModal: {
    width: s(360),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: BG,
    padding: s(18),
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(18),
  },
  modalTitle: {
    color: RED,
    fontSize: f(18),
    fontFamily: 'monospace',
  },
  modalClose: {
    width: s(30),
    height: s(30),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    height: s(44),
    borderWidth: 1,
    borderColor: '#6a4a4b',
    borderRadius: 4,
    color: TEXT_LIGHT,
    fontSize: f(14),
    fontFamily: 'monospace',
    paddingHorizontal: s(12),
    marginBottom: s(12),
    backgroundColor: 'rgba(75, 63, 63, 0.36)',
  },
  modalActions: {
    flexDirection: 'row',
    gap: s(12),
    marginTop: s(8),
  },
  authAction: {
    flex: 1,
    height: s(44),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PANEL,
  },
  authActionText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
  },

  topBarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
  },
  settingsGearButton: {
    height: s(36),
    width: s(36),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: s(10),
  },
  settingLabel: {
    color: TEXT_LIGHT,
    fontSize: f(14),
    fontFamily: 'monospace',
  },

  dogButton: {
    height: s(36),
    paddingHorizontal: s(14),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  dogButtonText: {
    color: RED,
    fontSize: f(13),
    fontFamily: 'monospace',
    maxWidth: s(100),
  },
  dogModal: {
    width: s(340),
    maxHeight: s(320),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: BG,
    padding: s(18),
  },
  dogList: {
    marginTop: s(4),
  },
  dogRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: s(12),
    borderBottomWidth: 1,
    borderBottomColor: '#3a2a2a',
  },
  dogRowSelected: {
    backgroundColor: 'rgba(242, 59, 63, 0.08)',
  },
  dogRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
    flex: 1,
  },
  dogName: {
    color: TEXT_LIGHT,
    fontFamily: 'monospace',
    fontSize: f(14),
  },
  dogNameSelected: {
    color: RED,
  },
  dogStatus: {
    fontSize: f(11),
    fontFamily: 'monospace',
    fontWeight: '700',
  },
  dogStatusActivo: { color: '#4caf50' },
  dogStatusInactivo: { color: '#888' },
  dogEmpty: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(13),
    textAlign: 'center',
    paddingVertical: s(20),
  },
  dogLoading: {
    paddingVertical: s(20),
    alignItems: 'center',
  },
  dogNewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    marginTop: s(14),
    paddingTop: s(12),
    borderTopWidth: 1,
    borderTopColor: '#3a2a2a',
  },
  dogNewInput: {
    flex: 1,
    height: s(38),
    borderWidth: 1,
    borderColor: '#6a4a4b',
    borderRadius: 4,
    color: TEXT_LIGHT,
    fontSize: f(13),
    fontFamily: 'monospace',
    paddingHorizontal: s(10),
    backgroundColor: 'rgba(75, 63, 63, 0.36)',
  },
  dogNewBtn: {
    width: s(38),
    height: s(38),
    borderWidth: 1,
    borderColor: '#f23b3f',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dogError: {
    color: '#f23b3f',
    fontFamily: 'monospace',
    fontSize: f(11),
    marginTop: s(8),
  },
  aiButton: {
    height: s(36),
    width: s(36),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  analysisModal: {
    width: s(440),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: BG,
    padding: s(18),
  },
  uploadArea: {
    height: s(180),
    borderWidth: 1,
    borderColor: '#6a4a4b',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: s(12),
    overflow: 'hidden',
  },
  uploadText: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(13),
    marginTop: s(8),
  },
  previewImage: {
    width: '100%' as any,
    height: '100%' as any,
  },
  analyzeButton: {
    height: s(44),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PANEL,
    marginBottom: s(12),
  },
  analyzeButtonText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
  },
  resultsContainer: { marginTop: s(4) },
  severityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(10),
  },
  severityLabel: {
    color: TEXT_LIGHT,
    fontFamily: 'monospace',
    fontSize: f(14),
  },
  severityBadge: {
    paddingHorizontal: s(12),
    paddingVertical: s(4),
    borderRadius: 4,
  },
  severityValue: {
    color: '#fff',
    fontFamily: 'monospace',
    fontWeight: '700',
    fontSize: f(15),
  },
  damagesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(6),
    marginBottom: s(10),
  },
  damageChip: {
    paddingHorizontal: s(10),
    paddingVertical: s(4),
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: 'rgba(242, 59, 63, 0.1)',
  },
  damageChipText: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(12),
  },
  summaryText: {
    color: TEXT_LIGHT,
    fontFamily: 'monospace',
    fontSize: f(13),
    lineHeight: f(20),
  },
});
