import { Platform, StyleSheet } from 'react-native';
import { s, f, d } from '../utils/scale';

const RED = '#E83D3D';
const BG = '#292222';
const PANEL = '#453A3A';
const TEXT_LIGHT = '#f6e7e7';
const LOGO_LIGHT = '#F8E3E3';
// JetBrains Mono and Viga are loaded in index.html for web; native falls back.
export const MONO = Platform.OS === 'web' ? '"JetBrains Mono", monospace' : 'monospace';
const VIGA = Platform.OS === 'web' ? 'Viga, sans-serif' : undefined;

export const styles = StyleSheet.create({
  window: {
    flex: 1,
    backgroundColor: BG,
    overflow: 'hidden',
  },

  topBar: {
    position: 'absolute',
    top: d(20),
    left: d(18),
    zIndex: 10,
  },
  statusPill: {
    height: d(26),
    paddingLeft: d(8),
    paddingRight: d(6),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: d(6),
  },
  statusText: {
    color: RED,
    fontSize: d(13),
    fontFamily: MONO,
    letterSpacing: 0.4,
  },
  pillMenu: {
    marginTop: d(4),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 3,
    backgroundColor: BG,
    overflow: 'hidden',
  },
  pillMenuItem: {
    paddingVertical: d(7),
    paddingHorizontal: d(8),
  },
  pillMenuText: {
    color: RED,
    fontSize: d(13),
    fontFamily: MONO,
    letterSpacing: 0.4,
  },
  authButton: {
    height: s(36),
    paddingHorizontal: s(14),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  authButtonText: {
    color: RED,
    fontSize: f(13),
    fontFamily: 'monospace',
  },

  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: d(24),
  },
  logoText: {
    width: d(361),
    height: d(139.5),
    marginBottom: d(33),
    color: LOGO_LIGHT,
    textAlign: 'center',
    fontFamily: VIGA,
    fontSize: d(104.638),
    fontWeight: '400',
  },
  logoAccent: {
    color: RED,
  },

  buttonWrapper: {
    flexDirection: 'row',
    gap: d(62),
  },
  mainButton: {
    width: d(221.292),
    height: d(58),
    borderRadius: d(5.354),
    borderWidth: d(1.785),
    borderColor: RED,
    backgroundColor: PANEL,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: RED,
    fontSize: d(16),
    fontFamily: MONO,
    letterSpacing: 1.2,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    paddingTop: s(72),
    paddingRight: s(28),
  },
  authModal: {
    width: s(360),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: BG,
    padding: s(18),
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(18),
  },
  modalTitle: {
    color: RED,
    fontSize: f(18),
    fontFamily: 'monospace',
  },
  modalClose: {
    width: s(30),
    height: s(30),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    height: s(44),
    borderWidth: 1,
    borderColor: '#6a4a4b',
    borderRadius: 4,
    color: TEXT_LIGHT,
    fontSize: f(14),
    fontFamily: 'monospace',
    paddingHorizontal: s(12),
    marginBottom: s(12),
    backgroundColor: 'rgba(75, 63, 63, 0.36)',
  },
  modalActions: {
    flexDirection: 'row',
    gap: s(12),
    marginTop: s(8),
  },
  authAction: {
    flex: 1,
    height: s(44),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PANEL,
  },
  authActionText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
  },

  topBarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
  },
  settingsGearButton: {
    height: s(36),
    width: s(36),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: s(10),
  },
  settingLabel: {
    color: TEXT_LIGHT,
    fontSize: f(14),
    fontFamily: 'monospace',
  },
  mediaSetting: {
    paddingTop: s(10),
    paddingBottom: s(6),
    gap: s(7),
    borderTopWidth: 1,
    borderTopColor: '#3a2a2a',
  },
  settingOptions: {
    flexDirection: 'row',
    gap: s(7),
  },
  settingOption: {
    flex: 1,
    minHeight: s(32),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#6a4a4b',
    borderRadius: 4,
    backgroundColor: 'rgba(75, 63, 63, 0.25)',
  },
  settingOptionActive: {
    borderColor: RED,
    backgroundColor: 'rgba(242, 59, 63, 0.14)',
  },
  settingOptionText: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(11),
  },
  settingOptionTextActive: {
    color: RED,
    fontWeight: '700',
  },
  settingHint: {
    color: '#6b5555',
    fontFamily: 'monospace',
    fontSize: f(10),
  },

  dogButton: {
    height: s(36),
    paddingHorizontal: s(14),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  dogButtonText: {
    color: RED,
    fontSize: f(13),
    fontFamily: 'monospace',
    maxWidth: s(100),
  },
  dogModal: {
    width: s(340),
    maxHeight: s(320),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: BG,
    padding: s(18),
  },
  dogList: {
    marginTop: s(4),
  },
  dogRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: s(12),
    borderBottomWidth: 1,
    borderBottomColor: '#3a2a2a',
  },
  dogRowSelected: {
    backgroundColor: 'rgba(242, 59, 63, 0.08)',
  },
  dogRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
    flex: 1,
  },
  dogName: {
    color: TEXT_LIGHT,
    fontFamily: 'monospace',
    fontSize: f(14),
  },
  dogNameSelected: {
    color: RED,
  },
  dogStatus: {
    fontSize: f(11),
    fontFamily: 'monospace',
    fontWeight: '700',
  },
  dogStatusActivo: { color: '#4caf50' },
  dogStatusInactivo: { color: '#888' },
  dogEmpty: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(13),
    textAlign: 'center',
    paddingVertical: s(20),
  },
  dogLoading: {
    paddingVertical: s(20),
    alignItems: 'center',
  },
  dogNewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    marginTop: s(14),
    paddingTop: s(12),
    borderTopWidth: 1,
    borderTopColor: '#3a2a2a',
  },
  dogNewInput: {
    flex: 1,
    height: s(38),
    borderWidth: 1,
    borderColor: '#6a4a4b',
    borderRadius: 4,
    color: TEXT_LIGHT,
    fontSize: f(13),
    fontFamily: 'monospace',
    paddingHorizontal: s(10),
    backgroundColor: 'rgba(75, 63, 63, 0.36)',
  },
  dogNewBtn: {
    width: s(38),
    height: s(38),
    borderWidth: 1,
    borderColor: '#f23b3f',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dogError: {
    color: '#f23b3f',
    fontFamily: 'monospace',
    fontSize: f(11),
    marginTop: s(8),
  },
  aiButton: {
    height: s(36),
    width: s(36),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(75, 63, 63, 0.58)',
  },
  analysisModal: {
    width: s(440),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: BG,
    padding: s(18),
  },
  uploadArea: {
    height: s(180),
    borderWidth: 1,
    borderColor: '#6a4a4b',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: s(12),
    overflow: 'hidden',
  },
  uploadText: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(13),
    marginTop: s(8),
  },
  previewImage: {
    width: '100%' as any,
    height: '100%' as any,
  },
  analyzeButton: {
    height: s(44),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PANEL,
    marginBottom: s(12),
  },
  analyzeButtonText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
  },
  resultsContainer: { marginTop: s(4) },
  severityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(10),
  },
  severityLabel: {
    color: TEXT_LIGHT,
    fontFamily: 'monospace',
    fontSize: f(14),
  },
  severityBadge: {
    paddingHorizontal: s(12),
    paddingVertical: s(4),
    borderRadius: 4,
  },
  severityValue: {
    color: '#fff',
    fontFamily: 'monospace',
    fontWeight: '700',
    fontSize: f(15),
  },
  damagesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(6),
    marginBottom: s(10),
  },
  damageChip: {
    paddingHorizontal: s(10),
    paddingVertical: s(4),
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: 'rgba(242, 59, 63, 0.1)',
  },
  damageChipText: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(12),
  },
  summaryText: {
    color: TEXT_LIGHT,
    fontFamily: 'monospace',
    fontSize: f(13),
    lineHeight: f(20),
  },
});
