import { StyleSheet } from 'react-native';
import { s, f } from '../utils/scale';

export const PIP_W = s(253);
export const PIP_H = s(143);

const RED = '#f23b3f';
const SCREEN_BG = '#292222';
const PANEL_BG = '#383535';
const CAMERA_GREY = '#626261';

export const styles = StyleSheet.create({
  window: {
    flex: 1,
    backgroundColor: SCREEN_BG,
  },

  videoStreamContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: SCREEN_BG,
    overflow: 'hidden',
  },
  lidarStreamContainer: { backgroundColor: CAMERA_GREY },
  liveFeedImage: {
    width: '100%' as any,
    height: '100%' as any,
  },
  videoPlaceholderText: {
    color: RED,
    fontSize: f(15),
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  lidarPlaceholderText: {
    color: '#161616',
    fontSize: f(15),
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  feedBadge: {
    position: 'absolute',
    left: s(10),
    bottom: s(10),
    minWidth: s(84),
    height: s(28),
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.68)',
    borderWidth: 1,
    borderColor: RED,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: s(8),
  },
  feedBadgeText: {
    color: RED,
    fontSize: f(10),
    fontFamily: 'monospace',
  },

  splitContainer: { flex: 1, flexDirection: 'row' },
  splitHalf: { flex: 1 },
  splitHalfRight: { borderLeftWidth: 2, borderColor: RED },

  pipWindow: {
    position: 'absolute',
    top: s(80),
    left: s(26),
    width: PIP_W,
    height: PIP_H,
    zIndex: 20,
    overflow: 'hidden',
    backgroundColor: CAMERA_GREY,
  },
  pipTouchable: { flex: 1 },
  pipSwapHint: { display: 'none' },
  pipSwapText: { color: RED, fontSize: f(8), fontFamily: 'monospace' },

  dragPreviewOverlay: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    zIndex: 15,
  },
  dragPreviewHalf: { flex: 1, overflow: 'hidden' },
  dragPreviewActive: { opacity: 0.65, borderWidth: 2, borderColor: RED },
  dragPreviewDim: { opacity: 0.25 },

  hudHeader: {
    position: 'absolute',
    top: s(16),
    left: s(16),
    right: s(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 50,
  },
  leftHudGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(12),
  },
  btnBack: {
    backgroundColor: '#000',
    height: s(42),
    width: s(90),
    borderRadius: 4,
    borderWidth: 2,
    borderColor: RED,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnBackActive: { backgroundColor: RED },
  btnFullScreen: {
    backgroundColor: '#000',
    height: s(42),
    width: s(76),
    borderRadius: 4,
    borderWidth: 2,
    borderColor: RED,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnFullActive: { backgroundColor: RED },
  btnText: {
    color: RED,
    fontSize: f(15),
    fontFamily: 'monospace',
  },
  btnTextActive: { color: '#161616' },

  telemetryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
  },
  telemetryText: {
    color: RED,
    fontSize: f(13),
    fontFamily: 'monospace',
  },
  lockButton: {
    width: s(34),
    height: s(28),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lockButtonActive: { backgroundColor: 'rgba(242, 59, 63, 0.12)' },

  rightHudGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
  },
  buildingsButton: {
    height: s(42),
    minWidth: s(120),
    paddingHorizontal: s(16),
    backgroundColor: '#cfcfcf',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buildingsButtonText: {
    color: '#171717',
    fontSize: f(14),
    fontFamily: 'monospace',
  },

  switchContainer: {
    width: s(48),
    height: s(26),
    borderRadius: s(13),
    backgroundColor: 'rgba(20, 20, 20, 0.85)',
    borderWidth: 1,
    borderColor: '#333',
    padding: 2,
    justifyContent: 'center',
  },
  switchActive: { borderColor: RED },
  switchThumb: {
    width: s(20),
    height: s(20),
    borderRadius: s(10),
    backgroundColor: '#444',
  },
  switchThumbActive: {
    backgroundColor: RED,
    alignSelf: 'flex-end',
  },

  controlsOverlay: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingBottom: s(24),
    paddingHorizontal: s(24),
  },
  joystickArea: {
    width: s(170),
    height: s(170),
    justifyContent: 'center',
    alignItems: 'center',
  },
  joystickBase: {
    width: s(170),
    height: s(170),
    borderRadius: s(85),
    backgroundColor: '#dddddd',
    justifyContent: 'center',
    alignItems: 'center',
  },
  joystickStick: {
    width: s(72),
    height: s(72),
    borderRadius: s(36),
    backgroundColor: '#626262',
  },

  actionContainer: {
    flex: 1,
    height: s(60),
    marginHorizontal: s(16),
    justifyContent: 'center',
  },
  actionScroll: {
    backgroundColor: PANEL_BG,
    borderRadius: 8,
    maxWidth: '100%',
    alignSelf: 'center',
  },
  actionScrollContent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: s(24),
  },
  actionButton: {
    height: s(60),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: s(12),
    backgroundColor: 'transparent',
  },
  actionSeparator: {
    color: RED,
    fontSize: f(16),
    fontFamily: 'monospace',
    marginRight: s(12),
  },
  actionButtonText: {
    color: RED,
    fontSize: f(13),
    fontFamily: 'monospace',
  },

  pushMenu: {
    backgroundColor: SCREEN_BG,
    borderLeftWidth: 1,
    borderColor: '#433838',
    overflow: 'hidden',
  },
  menuInnerContent: {
    flex: 1,
    padding: s(16),
  },
  menuCloseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: s(16),
  },

  edificioCard: {
    marginBottom: s(12),
    borderWidth: 1,
    borderColor: '#433838',
    borderRadius: 4,
    padding: s(10),
  },
  edificioCardHeader: {
    flexDirection: 'row',
    marginBottom: s(6),
  },
  edificioThumb: {
    width: s(68),
    height: s(52),
    borderRadius: 3,
    backgroundColor: '#222',
    marginRight: s(10),
  },
  edificioInfo: { flex: 1 },
  edificioName: {
    color: '#f6e7e7',
    fontFamily: 'monospace',
    fontWeight: '700',
    fontSize: f(12),
    marginBottom: s(5),
  },
  edificioBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: s(8),
    paddingVertical: 2,
    borderRadius: 4,
  },
  edificioBadgeText: {
    color: '#fff',
    fontFamily: 'monospace',
    fontSize: f(11),
    fontWeight: '700',
  },
  edificioResumen: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(11),
    lineHeight: f(15),
    marginTop: s(4),
  },

  siguienteButton: {
    marginTop: s(12),
    height: s(42),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(242, 59, 63, 0.12)',
  },
  siguienteButtonText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
    letterSpacing: 1,
  },

  sliderWrapper: {
    position: 'absolute',
    top: s(240),
    left: 0,
    height: s(52),
    justifyContent: 'center',
    zIndex: 100,
  },
  sliderWrapperSplit: { top: s(120) },
  sliderBar: {
    height: s(36),
    backgroundColor: '#000',
    borderRadius: 4,
    borderWidth: 2,
    borderColor: RED,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: s(15),
  },
  sliderBarActive: { backgroundColor: RED, borderColor: RED },
  sliderText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
  },
  sliderTextActive: { color: '#161616' },

  dpadArea: {
    width: s(170),
    height: s(170),
    alignItems: 'center',
    justifyContent: 'center',
  },
  dpadBtn: {
    width: s(52),
    height: s(52),
    borderRadius: 6,
    backgroundColor: '#dddddd',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dpadBtnSmall: {
    width: s(36),
    height: s(36),
    borderRadius: 4,
    backgroundColor: '#b0b0b0',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: s(2),
  },
  dpadSmallText: {
    color: '#161616',
    fontSize: f(11),
    fontFamily: 'monospace',
    fontWeight: '700',
  },
  dpadMiddleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: s(4),
  },
  dpadCenter: {
    width: s(52),
    height: s(52),
    marginHorizontal: s(4),
  },

  speedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(6),
    marginTop: s(14),
    paddingTop: s(10),
    borderTopWidth: 1,
    borderTopColor: '#2a1a1a',
  },
  speedLabel: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(12),
  },
  speedValue: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(13),
    fontWeight: '700',
    minWidth: s(36),
    textAlign: 'center' as const,
  },
  speedBtn: {
    width: s(30),
    height: s(30),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    justifyContent: 'center',
    alignItems: 'center',
  },
  speedBar: {
    flex: 1,
    height: s(6),
    backgroundColor: '#2a1a1a',
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  speedFill: {
    height: '100%' as any,
    backgroundColor: RED,
    borderRadius: 3,
  },
  autoRow: {
    flexDirection: 'row',
    gap: s(6),
    marginTop: s(8),
  },
  autoBtn: {
    flex: 1,
    height: s(34),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#45d483',
    backgroundColor: 'rgba(69,212,131,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  autoBtnStop:      { borderColor: '#ffb347', backgroundColor: 'rgba(255,179,71,0.1)' },
  autoBtnEmergency: { borderColor: RED,       backgroundColor: 'rgba(242,59,63,0.15)' },
  autoBtnText:          { color: '#45d483', fontFamily: 'monospace', fontSize: f(10), fontWeight: '700' as const },
  autoBtnTextStop:      { color: '#ffb347' },
  autoBtnTextEmergency: { color: RED },
  autoStatusDot: {
    width: s(8), height: s(8), borderRadius: s(4),
    marginRight: s(6),
  },
  telemetryBox: {
    backgroundColor: '#0e1822',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#2c3f53',
    padding: s(8),
    marginTop: s(8),
  },
  telemetryLine: {
    color: '#9ab0c3',
    fontFamily: 'monospace',
    fontSize: f(10),
    lineHeight: f(15),
  },
  stopHudBtn: {
    height: s(42),
    paddingHorizontal: s(12),
    borderRadius: 4,
    borderWidth: 2,
    borderColor: RED,
    backgroundColor: 'rgba(242,59,63,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stopHudText: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(13),
    fontWeight: '700' as const,
  },

  aiHudButton: {
    width: s(42),
    height: s(42),
    borderWidth: 2,
    borderColor: RED,
    borderRadius: 4,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },

  aiModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiModal: {
    width: s(420),
    maxHeight: s(500),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: SCREEN_BG,
    padding: s(18),
  },
  aiModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(12),
  },
  aiModalTitle: {
    color: RED,
    fontSize: f(17),
    fontFamily: 'monospace',
  },
  aiModalClose: {
    width: s(34),
    height: s(34),
    borderWidth: 1,
    borderColor: RED,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadArea: {
    height: s(160),
    borderWidth: 1,
    borderColor: '#433838',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: s(12),
    overflow: 'hidden',
    backgroundColor: PANEL_BG,
  },
  uploadText: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(13),
    marginTop: s(8),
  },
  previewImage: {
    width: '100%' as any,
    height: '100%' as any,
  },
  analyzeButton: {
    height: s(42),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PANEL_BG,
    marginBottom: s(10),
  },
  analyzeButtonText: {
    color: RED,
    fontSize: f(14),
    fontFamily: 'monospace',
  },
  resultsContainer: { marginTop: s(4) },
  severityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(8),
  },
  severityLabel: {
    color: '#f6e7e7',
    fontFamily: 'monospace',
    fontSize: f(14),
  },
  severityBadge: {
    paddingHorizontal: s(12),
    paddingVertical: s(4),
    borderRadius: 4,
  },
  severityValue: {
    color: '#fff',
    fontFamily: 'monospace',
    fontWeight: '700',
    fontSize: f(15),
  },
  gradeText: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(12),
    marginBottom: s(8),
  },
  damagesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(6),
    marginBottom: s(8),
  },
  damageChip: {
    paddingHorizontal: s(10),
    paddingVertical: s(4),
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: 'rgba(242, 59, 63, 0.1)',
  },
  damageChipText: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(12),
  },
  summaryText: {
    color: '#f6e7e7',
    fontFamily: 'monospace',
    fontSize: f(13),
    lineHeight: f(19),
  },

  operatorSection: {
    borderWidth: 1,
    borderColor: '#433838',
    backgroundColor: 'rgba(0,0,0,0.16)',
    borderRadius: 4,
    padding: s(8),
    gap: s(8),
  },
  operatorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: s(6),
  },
  operatorHint: {
    color: '#6f5a5a',
    fontFamily: 'monospace',
    fontSize: f(10),
    lineHeight: f(14),
  },
  statusChip: {
    minHeight: s(24),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#433838',
    backgroundColor: '#171313',
    paddingHorizontal: s(8),
    paddingVertical: s(4),
    justifyContent: 'center',
  },
  statusChipOk: {
    borderColor: '#285a41',
    backgroundColor: 'rgba(69,212,131,0.08)',
  },
  statusChipWarn: {
    borderColor: '#73552d',
    backgroundColor: 'rgba(255,179,71,0.08)',
  },
  statusChipErr: {
    borderColor: RED,
    backgroundColor: 'rgba(242,59,63,0.1)',
  },
  statusChipText: {
    color: '#9a8a8a',
    fontFamily: 'monospace',
    fontSize: f(10),
  },
  operatorButton: {
    minHeight: s(30),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: RED,
    backgroundColor: 'rgba(242,59,63,0.08)',
    paddingHorizontal: s(10),
    paddingVertical: s(6),
    justifyContent: 'center',
    alignItems: 'center',
  },
  operatorButtonOk: {
    borderColor: '#45d483',
    backgroundColor: 'rgba(69,212,131,0.08)',
  },
  operatorButtonWarn: {
    borderColor: '#ffb347',
    backgroundColor: 'rgba(255,179,71,0.08)',
  },
  operatorButtonDanger: {
    borderColor: RED,
    backgroundColor: 'rgba(242,59,63,0.16)',
  },
  operatorButtonText: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(10),
    fontWeight: '700' as const,
  },
  profileRow: {
    flexDirection: 'row',
    gap: s(6),
  },
  profileButton: {
    flex: 1,
    minHeight: s(30),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#433838',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#171313',
  },
  profileButtonActive: {
    borderColor: RED,
    backgroundColor: 'rgba(242,59,63,0.13)',
  },
  profileButtonText: {
    color: '#7b6868',
    fontFamily: 'monospace',
    fontSize: f(10),
    fontWeight: '700' as const,
  },
  profileButtonTextActive: {
    color: RED,
  },
  operatorSwitchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: s(8),
  },
  operatorSwitchLabel: {
    color: '#9a8a8a',
    fontFamily: 'monospace',
    fontSize: f(10),
    fontWeight: '700' as const,
  },
  numberGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(8),
  },
  numberField: {
    width: s(110),
    gap: s(4),
  },
  numberLabel: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(9),
  },
  numberControls: {
    height: s(30),
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#433838',
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#171313',
  },
  numberStep: {
    width: s(28),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#211919',
  },
  numberStepText: {
    color: RED,
    fontFamily: 'monospace',
    fontSize: f(14),
    fontWeight: '700' as const,
  },
  numberInput: {
    flex: 1,
    color: '#f6e7e7',
    fontFamily: 'monospace',
    fontSize: f(10),
    textAlign: 'center' as const,
    padding: 0,
    outlineStyle: 'none' as any,
  },
  mapChoice: {
    maxWidth: s(220),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#433838',
    backgroundColor: '#171313',
    paddingHorizontal: s(8),
    paddingVertical: s(7),
  },
  mapChoiceActive: {
    borderColor: RED,
    backgroundColor: 'rgba(242,59,63,0.12)',
  },
  mapChoiceText: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(10),
  },
  mapChoiceTextActive: {
    color: RED,
  },
  savedMapPreview: {
    height: s(170),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#2c3f53',
    overflow: 'hidden',
    backgroundColor: '#070c12',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savedMapPlaceholder: {
    color: '#253342',
    fontFamily: 'monospace',
    fontSize: f(13),
  },
  faceCard: {
    width: s(96),
    borderWidth: 1,
    borderColor: '#433838',
    borderRadius: 4,
    padding: s(6),
    backgroundColor: '#171313',
  },
  faceImage: {
    width: '100%' as any,
    height: s(72),
    borderRadius: 3,
    backgroundColor: '#0b0b0b',
  },
  faceLabel: {
    color: '#f6e7e7',
    fontFamily: 'monospace',
    fontSize: f(10),
    marginTop: s(5),
  },
  faceMeta: {
    color: '#8b7474',
    fontFamily: 'monospace',
    fontSize: f(9),
    marginTop: s(2),
  },
});
